### ISSUE TITLE
launch.json instructions don't work

### ISSUE THREAD

**Issue by Velkas** [orta/vscode-playdate#2]
Seems something changed with the VSCode spec because I get the errors that "source" and "output" are not valid so per your instructions, the launch.json and tasks.json files don't work. I'm not actually sure how to fix this myself unfortunately.

**Comment by bombsimon** [comment]
There is now new instructions in the [README](https://github.com/orta/vscode-playdate#run-as-debugger) and you can also use the command from the command pallet without setting up any launch configuration at all.

I'm closing this issue since it's pretty old and before the rewrite but please open a new one if there's something not working for you.
