### ISSUE TITLE
can't able to re-configure source & output path

### ISSUE THREAD

**Issue by Jeyanthinath** [orta/vscode-playdate#23]
When I tried to configure the new paths, the vscode is saying, these options are invalid.

Also, these options are not considered while running the extension. So I can't able to re-configure the path and use this extension. I am right now renamed my folder from src to source to run this.

Any help will be appreciated

I am using the latest playdate sdk.

<img width="974" alt="Screenshot 2022-07-25 at 12 15 26 AM" src="https://user-images.githubusercontent.com/2253649/180661534-f6b98ed9-57f2-4dc1-b090-e6239897983c.png">

```
jae@mac Contents % pdc --version
1.12.2
jae@mac Contents % 
```

**Comment by bombsimon** [comment]
If the folder where the output should be created does not exist the compilation will fail (sadly without an error message from the plugin). This also happens when just using the compiler and since that's not supported I don't think this plugin should support it:

```sh
$ pdc src/ bin/Output.pdx
error: Couldn't create folder at bin/Output.pdx

$ mkdir bin

$ pdc src/ bin/Output.pdx && echo $?
0
```

I'll have a look to see why the settings are not considered valid because if I put my source files in `src` and creats the `bin` directory, the configuration you're using works for me:

```json
{
  "playdate.source": "src",
  "playdate.output": "bin/Output.pdx",
}
```
